# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87b2ddc2f16dcbf261a82f50d9853e51fa2d4e98e00f0032582187fa454562cdf93dc17a8d6c827027d3caa01b3c40b0df7715cdcaa61a454ffcd761cb214c8e

test:
  secret_key_base: 4801870167425e1fb955352ad5e4e2a0c23101cde61ada2b8d8eeb1ef2b7f8ea2ec0c616ee5c16c506b014f0dbd66ade0463775a84ef2b4cdab7ccec78e73983

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
